
import CompanyPage from './CompanyPage';

export async function generateStaticParams() {
  return [
    { name: 'turkcell' },
    { name: 'vodafone' },
    { name: 'zara' },
    { name: 'migros' },
    { name: 'getir' },
    { name: 'teknosa' },
    { name: 'h&m' },
    { name: 'carrefoursa' },
    { name: 'yemeksepeti' },
    { name: 'türk-telekom' },
    { name: 'mango' },
    { name: 'lcw' },
    { name: 'lc-waikiki' },
    { name: 'lc%20waikiki' },
    { name: 'defacto' },
    { name: 'koton' },
    { name: 'trendyol' },
    { name: 'hepsiburada' },
    { name: 'n11' },
    { name: 'gittigidiyor' },
    { name: 'amazon' },
    { name: 'netflix' },
    { name: 'spotify' },
    { name: 'uber' },
    { name: 'yandex' },
    { name: 'taksim' },
    { name: 'bim' },
    { name: 'a101' },
    { name: 'şok' },
    { name: 'carrefour' },
    { name: 'real' },
    { name: 'macro' },
    { name: 'bauhaus' },
    { name: 'koçtaş' },
    { name: 'ikea' },
    { name: 'mediamarkt' },
    { name: 'vatan' },
    { name: 'gold' },
    { name: 'boyner' },
    { name: 'vakko' },
    { name: 'beymen' },
    { name: 'nike' },
    { name: 'adidas' },
    { name: 'puma' },
    { name: 'mcdonalds' },
    { name: 'burger-king' },
    { name: 'kfc' },
    { name: 'dominos' },
    { name: 'pizza-hut' },
    { name: 'starbucks' },
    { name: 'gloria-jeans' },
    { name: 'tchibo' },
    // URL-encoded versions for all companies with spaces
    { name: 'türk%20telekom' },
    { name: 'turk%20telekom' },
    { name: 'burger%20king' },
    { name: 'pizza%20hut' },
    { name: 'gloria%20jeans' },
    { name: 'yemek%20sepeti' },
    { name: 'media%20markt' },
    { name: 'h%26m' },
    // Alternative encodings
    { name: 'lc+waikiki' },
    { name: 'türk+telekom' },
    { name: 'burger+king' },
    { name: 'pizza+hut' },
    { name: 'gloria+jeans' },
    // Common typos and variations
    { name: 'waikiki' },
    { name: 'lcwaikiki' },
    { name: 'lc_waikiki' },
    { name: 'turktelekom' },
    { name: 'turk-telekom' }
  ];
}

export default function CompanyPageRoute({ params }: { params: { name: string } }) {
  return <CompanyPage companyName={params.name} />;
}
